### PR TITLE
moosecounter - Polishing

### PR DESCRIPTION
**Pull request by steffilazerte**
## Final To-Do

- [x] Explore PI
  - [x] Interactive table and map to show surveyed areas/cells/points
- [x] Double check Dependencies, etc. (kableExtra)
- [x] Options formatting, elegantly presenting selected options
- [x] Shiny Tests
- [x] Final checks in `RELEASE.R`

## For Later / Consideration

- [ ] Documentation
  - [ ] Home
  - [ ] Docs
  - [ ] Tooltips
- [ ] Remember previous settings/session (Bookmarking state?)
- [ ] Add option for specifying meta/response/etc variables" (comment)

### CODE REVIEW

**Comment by psolymos** [comment]
Hi @steffilazerte I added a download button to the PI data exploration tab. I also reorganized the columns in PI data (`mc_get_pred(pi()$pi)$data`) so that users won't have to scroll that much.

**Comment by steffilazerte** [comment]
@psolymos Got the selection working! The reason why selecting only 1 row didn't work was because ggiraph requires the selection to be character 🤷🏼 (for future reference). Code also catches any selection made on the map directly and redirects it to the row selection (couldn't make it unselect all without feedback loops). So now you select/unselect by clicking on the rows, and use the reset button to clear everything (I think we'll need some fancier JS to catch DT sorting, so I left it out for now). 

Also set seed and modified the issues in the PI table.

Next to do: 

- Dropdown for colour selection
- Update/add to shiny tests
- Final checks

Getting close!

**Comment by psolymos** [comment]
Thanks @steffilazerte ! I tried the new version, works smooth. I suspected that watching the sort event could be tricky, reset button will be fine.

> Dropdown for colour selection

Do you mean dropdown to select which variable to show on the map?

One minor thing: `fitted_values` and `Residuals` should be rounded to 3 digits (not in the reactive data but just  in the DT render function), not it prints zillion digits. As I recall DT has some arguments/options for this purpose too.

**Comment by steffilazerte** [comment]
Yes, to select the variable to map to colour/fill. I'll round the zillion digits too :grin:

**Comment by steffilazerte** [comment]
Hi @psolymos, I think I'm done everything except the final shiny tests and checks. So if you get a chance today, why don't you take a look. Let me know if you can think of anything else!

One thing that I'm not sure about... if the models change (by changing the Settings, for example), the Prediction Intervals tab will tell you that you should update the PIs, but the Explore predictions tab doesn't say anything... Should it give the users a message too? Or should we assume that it's fine as long as it's in the PI tab?

**Comment by steffilazerte** [comment]
Hi @psolymos,

It's done! Shiny tests took a bit of time because the new svg map was 

a) not respecting the random seed, so generated a new svg id everytime which triggered shiny tests to error
b) so big it caused everything to freeze up when I did the comparisons 🤦🏼 

So right now, the app tests that there are no show stopping errors when running the "Explore predictions" tab, but doesn't actually take any snapshots at that stage. It's possibly something to ask ggiraph or shinytest people about, but for now, I'll leave it as is. 

Let me know if you have any other things to add!

**Comment by psolymos** [comment]
Thanks @steffilazerte I'll check and merge if all OK. No need for snapshots for now.

The PI update if the model changes: let's assume users know what they are doing. Keep this on the "For later" list. I created #11 to keep tab of these.

**Comment by psolymos** [comment]
@steffilazerte all looks good, thanks so much!

The only note I have is that the shinytest is making the package really heavy. It would be nice to make the testing optional (i.e. as part of a script, but not necessarily as part of R CMD check). The `inst/shiny/tests` directory was flagged to be 2x as big as the package itself.

We can also think about how to differentiate the "Shiny app dependencies" vs. "Development dependencies". Now these are all listed under `Suggests`, but the development deps are not required for the app. I chose to manually list the 'real' dependencies in the `README.md` file and in the `/inst/tmp/Dockerfile` (this is what I used to test if a fresh install leads to a working app). I am not sure what the right solution is, this is one of my general frustrations with the `Suggests` field and you know my aversion of too many deps :)

**Comment by steffilazerte** [comment]
To remove the shinytests from a user's install we can do the following:

1. prevent it running as part of R CMD check, omit the `tests/testthat/test_app.R` file and then just run it by hand with the `RELEASE.R` script. You could also remove the testthat package dependency then.

2. prevent it from being built by adding `^.*/shiny/tests/.*$` to the `.Rbuildignore` file

That only leaves the shinytest as a developmental dependency, right? For users, the easiest thing is to leave that one in suggests, and move all the others to depends, then have the users just install depends (not suggests). I think by default that's what the `remotes::install_github()` [function does](https://remotes.r-lib.org/reference/install_github.html). 

Let me know if you'd like me to make these changes!

Also, in the future I can probably get rid of the dplyr dep if you prefer (I'm holding onto purrr and `imap()` though! :grin:)

**Comment by psolymos** [comment]
I am fine with purrr and dplyr :) That is needed for the "business logic"

I commented out a few lines for now, so you recommendation is half implemented.

We can also consider moving the ui and server function into /R and export it. Then we can declare most suggested packages as imports and keep shinytest in suggests. This is a bit more work, so shelve it for later.

**Pull request merged**
