### PR TITLE
Shiny UI for moosecounter

### LINKED ISSUE #7: Inconsistent factor levels for AIC table
After converting `GMS` to factor, the model AIC table fails because the factor levels are different (I have no idea why they would be, but it looks like the levels in the model object aren't the complete set?!?)

``` r
library(moosecounter)
#> This is moosecounter 0.4-0    2021-08-19

x <- read.csv(system.file("extdata",
                          "UKH2017_MMU_Querried_data_for_Analysis_Final_3.csv",
                          package = "moosecounter"))

## set response in options
switch_response("total")

## define surveyed units and take a subset as needed
## this also sets total cows value
x <- mc_update_total(x)

x$GMS <- as.factor(x$GMS)

## build model list
ML <- list()
ML[["Model 1"]] <- mc_fit_total(x,
                                vars = c("GMS"),
                                dist="P", weighted=FALSE)

mc_models_total(ML, x)
#> Error in model.frame.default(delete.response(object$terms$full), newdata, : factor GMS has new levels 252, 253, 309
```

<sup>Created on 2021-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by steffilazerte**
Hi @psolymos,

This is the draft fork which I'll continue to modify as I work on the Shiny UI. Feel free to check it out, make comments etc. 

I'll leave this as a draft for now, and will continue to update this comment with my list of things to do as we go along. (We can also use issues too, if that works better). I tend to start with broad To Dos, and get more specific as we get closer to being done, or run into more fiddly problems.

### To Do

**Basic Content**
- [X] Settings
  - [X] UI to set options
  - [X] reactive to keep options current in models, etc.
  - [X] Do we need option settings for surveyed units/area? Nope
- [x] Data
  - [X] Loading data
  - [X] Add tab to confirm data structure and types 
  - [X] Filtering/Transforming data
    - [x] Double check variables from google sheet
    - [x] Identify categorical columns with selectize and make them factors
    - [x] Omit factors (either integer and potentially factor, or character, or factor [only relevant for old versions of R and read.csv]) which are missing levels in the surveyed data (fixes #7)
- [x] Exploration
  - [X]  Univariate
  - [x] Multivariate
    - [x] Add p-value slider (waiting for @psolymos to modify `mc_plot_multivariate()`)
    - [x] **Seems off, adding more variables doesn't expand figure; look into variables**
- [x] Models
  - [X] Create models
     - [X] Null models ([comment](https://github.com/psolymos/moosecounter/pull/1#issuecomment-917301153))
     - [x] Table of model coefficients (waiting for @psolymos to implement first)
  - [x] Ability to remove models
  - [x] ~~Don't overwrite models~~ [*Changed my mind*]
  - [X] Add default/dynamic model naming, so overwriting can only occur semi-deliberately
  - [x] What happens if data set changes? Hopefully just causes model errors and they can be removed...
- [x] Residuals
  - [x] repeat AIC summary table here
- [x] Calculate PI
  - [X] Choose model(s)
  - [X] Choose averaging/best
  - [x] Make "Calculate Prediction Intervals" button dynamic: if Settings or Models change, set as "red" and "Update to match settings" (or similar) [Could update automatically, like models now do, but could get tedious as call takes a while]
  - [X] Output tables and figures
    - [X] `mc_plot_pidistrcell` should accept a cell ID, i.e. `mc_plot_pidistrcell(PI(), id=input$cellid)`
   - [X]  total & cell level PI plot into mc_plot_pidistr, it can be a single tab in the UI or 2 separate ones (as now), up to you
  - [X] Add optional shiny progress bar to `mc_predict_total()` (https://shiny.rstudio.com/articles/progress.html)
  - [X] Add third box to left showing active options
  - [X] Cell to plot should omit or identify surveyed blocks
  - [X] Table row names should be words (rather than N, A, D) (waiting for @psolymos to make internal change)
- [ ] Explore PI
  - [ ] Interactive table and map to show surveyed areas/cells/points

**Polishing**
- [ ] Double check Dependencies, etc. (`kableExtra`)
- [ ] Options formatting, elegantly presenting selected options
- [x] Be more consistent with Tab style (columns vs. boxes, etc.)
- [ ] Shiny Tests

**For Later / Consideration**
- [ ] Documentation
  - [ ] Home
  - [ ] Docs
  - [ ] Tooltips
- [ ] Remember previous settings/session (Bookmarking state?)
- [ ] Add option for specifying meta/response/etc variables" ([comment](https://github.com/psolymos/moosecounter/pull/1#issuecomment-917301153))

### CODE REVIEW

**Comment by psolymos** [comment]
Thanks @steffilazerte looks really good so far. Like the options table and how the "Add model" piece advances to the next mode name.

I saw the {purrr} added to `DESCRIPTION` but Shiny complains about not finding `map`, `imap` etc. Needs to be called as `map::` or add `library(purrr)` to `global.R`.

The TODO list and the PR will work fine. Looking forward to the rest!

**Comment by steffilazerte** [comment]
Oh and that reminds me, I've tried to avoid tidyverse packages because I had the sense that you preferred lightweight dependencies, is it okay to have purrr (and magrittr, which is imported by purrr)? What about dplyr? Some of these I can get around, but it can be easier to code with them at times (purrr and imap especially).

**Comment by psolymos** [comment]
Yes, my personal preference is to keep deps to a minimum, but I am fine with bringing in more of these quite mature APIs :)

**Comment by steffilazerte** [comment]
The app isn't polished, but I think all the pieces are there. I still need to double check against the docs you sent me to make sure I've included everything and have a couple more things to check, but feel free to play around and let me know what you think.

**Comment by psolymos** [comment]
Great! Thank you. I'll check the app and let you know.

**Comment by psolymos** [comment]
@steffilazerte great progress so far. I haven't looked at the code, just the app. Here are some comments:

- I am thinking if the filters on the data tab (survey name, region, year, survey ID) should be hard coded or maybe added as options, not critical but would make the app more general
- ability to add Null model (count model input is empty), this is not working, it is a `mc_fit_total` that I'll address, this should take care of it
- spinner or a progress bar when calculating PI would be useful: we don't really know the progress but something to indicate that something is happening. If I click again, the app becomes unresponsive until the next calculation finished, so it is best to indicate the work being done, even if the progress bar is not moving, e.g. show 50% then jump to 100% when done
- I'll think about the Moose in cell output, how to best do that. `mc_plot_pidistrcell` should accept a cell ID, i.e. `mc_plot_pidistrcell(PI(), id=input$cellid)`

**Comment by psolymos** [comment]
Updates in #3 :

- changed the `mc_fit_total(x, vars=NULL, zi_vars=NULL)` arguments (order & defaults) so that the Null model will work from the Shiny UI, please check that the reactives reference the arguments correctly
- unified the total & cell level PI plot into `mc_plot_pidistr`, it can be a single tab in the UI or 2 separate ones (as now), up to you
- also fixed #2

**Comment by steffilazerte** [comment]
Hi @psolymos,
Still stuff to work on, but the next set of edits are:
- Progress bar added (I needed to make changes to total.R, let me know if that's okay)
- Models are dynamically updated if settings change (the method setting only applies to the PI calculations, is that expected behaviour?)
- Model errors result in a note and requests for the user to fix/remove the model (this way a change in settings which invalidates a model won't cause crashes) [You can play with this behaviour by uncommenting the "TESTING errors" section in the `models()` reactive which will introduce an error on any model called "C"]
- Adjusted inputs for NULLs in all count/zero variables
- Adjusted PI plots and added Cell input for figures.

**Comment by psolymos** [comment]
Hi @steffilazerte : super cool so far 👍🏼

Adding the Shiny progress bar inside `mc_predict_total` is genius - I totally forgot that the pb was updated in the loop.

The **method setting** should apply to the model and whatever method was used in the model the PI function will recognize. This is a good catch b/c I don't think it is handled correctly now. Both `wzi` and `mc_predict_total` take it from the Moose options, but `zeroinfl2` can have a different setting.  But the point is that the model should have the method as a requirement. See commit add20b416db22a6948843e4503fb1bb9db75461b

Other points: updates work great. Found 1 issue: on the Totals/Models panel I get an error:

```
Warning: Error in data.frame: 'row.names' should specify one of the variables
  103: stop
  102: data.frame
  101: .f
  100: map2
   99: map2_dfr
   98: imap_dfr
   97: renderTable [/Library/Frameworks/R.framework/Versions/4.1/Resources/library/moosecounter/shiny/server.R#179]
```

Screen Shot 2021-09-13 at 9 29 48 PM

**Comment by psolymos** [comment]
@steffilazerte please add yourself to the package authors in the `DESCRIPTION`.

**Comment by steffilazerte** [comment]
Thanks! Will do

**Comment by psolymos** [comment]
FYI: progress bar for shiny UI is forthcoming in pbapply 1.5, https://github.com/psolymos/pbapply#shiny

**Comment by steffilazerte** [comment]
Hi @psolymos 

Today's update includes:
- Fixing the error on the model selection tab
- Omit "Brent" as a method
- Fixed a problem with the zero variables input
- Switched to the pbapply shiny progress (check if it makes sense? it seems to work, but I'm not sure if that's the process you had in mind)
- Added formatting to make buttons more visible, highlight model errors (test by creating a model with one data set then change the dataset), warn user when models have changed, but PIs have not been updated
- Added a bunch of validate() catches to let the user know what they need to do before each step
- Add table with PI options

Next I'll start cleaning up, checking things and adding Shiny Tests. Let me know if you find anything that needs to change!

**Comment by psolymos** [comment]
Hi @steffilazerte , thanks for addressing the issues. I have received feedback from the power users (n=3) of the app, so I'll outline **my** observations/suggestions 1st, then **theirs**. I also add initials for who could take a stab at each [S=Steffi, P=Peter]

Peter's notes:

- let's move the Documentation piece to **Later** in your todo list, so that we won't have to revise extensively if UI changes (users will have a pretty good idea based on the old JGR/Deducer interface) **[S]**
- would make sense to repeat the AIC summary table above the Residual plots so that users don't have to go back and forth **[S]**
- I will work a bit on the XY plots (map-like ones) to make aspect ratio 1:1 but this is an area we will need to thing more strategically (see user feedback, we might need leaflet & crosstalk if we have room left at the end) **[P]**
- for `Suggest` field we need to add the markdown and kableExtra **[S]**

User feedback: overall "_looks amazing, super slick_" and "_this is great and much more intuitive than the last version_" -- thanks to you @steffilazerte !

The easy to implement ones:

- add an independent/separate slider for the p-value **just for the multivariate** analysis, and keep the current alpha level option for the parametric model/prediction -- `mc_plot_multivariate` will expose `alpha` and fall back to `opts$alpha` only when the arg is missing (this could be related to your remark about **Seems off, adding more variables doesn't expand figure**. **[P then S]**
- Data reading: on data upload tab add a selection (multiple selectize for column names) to identify categorical variables. This is important because all the expert data is categorical but could possibly entered as integers. **[S]**
- Univariate exploration: add the ability to plot relationships with categorical predictors, `mc_plot_univariate` should recognize when `x[[i]]` is character or factor (will be set by previous point: Data reading) **[P]**
- See what the coefficients look like for individual models (not just one, but 2 to compare, or possibly all). MuMIn package has this functionality, which was used before, so this needs to be added to CLI and UI **[P then S]**
- Cell to plot for predictions: omit surveyed blocks for the individual block predictions, or something that indicated that the block was surveyed. **[S]**
- Prediction interval summary: use words for N, A, D. **[P]**
  - N for total moose
  - A for total area (km2), 
  - D for Density (moose/1000km2). Could we have 3 decimals for moose density because it’s moose/1000 km2.

The feature that would be super useful for the actual survey design in the field: this relates to the data that they need to be able to download (so that they can manipulate it in GIS etc). Which could be mute, and be done in Shiny with an interactive map+table combo:

> Need PI table from old program. We need to have that table of predictions by SU to pick survey blocks for the next day. If ever this page could have the table on one side and the map on the other and identify a certain number of blocks with the greatest error that would be very slick. For example – user would select number of blocks with the greatest error and then they would show up on the map. It would be nice to be able to scroll through the entire table just like in your data window.

I imagine the same can be done for the residual analysis, so that it is added there too, or all this is separated into a new tab where you can select what to show in the map. Let's leave this for now and come back to it and discuss once the rest is done.

**Comment by steffilazerte** [comment]
Great! Glad to hear that things are on the right track. I'll modify the priorities and then get started!

**Comment by steffilazerte** [comment]
Just went through all the comments in more detail, with respect to the final comment, what about using ggplot2 (geom_sf) + ggiraph? I find it pretty slick, especially if you don't need all the panning requirements of leaflet.

**Comment by psolymos** [comment]
The flow is going to be table-to-map, so the results will dictate the map aesthetics and not the map dictating the tabular results. So the ggplot2 based solution might be a good choice. I can also imagine a range-slider for the residuals etc. to define cutpoints (points/cells outside of the interval get highlighted).

The reason why I was thinking of leaflet or plotly is that popup that can hold a lot of info. But we have the table there too with the same info.

So maybe what we need is (1) some general inputs to define styling/thresholds, and (2) interactivity between the table and map to highlight the same points & rows.

Hope this is making sense. Thoughts?

**Comment by psolymos** [comment]
@steffilazerte Internal changes are good to go from my end (see changes on my main branch).

**Comment by steffilazerte** [comment]
> The reason why I was thinking of leaflet or plotly is that popup that can hold a lot of info. But we have the table there too with the same info.
 
ggiraph can give you tooltips and quite complex interactivity (e.g., https://davidgohel.github.io/ggiraph/articles/offcran/examples.html#ceo-voluntary-and-involuntary-departures), so we could keep it simple AND have some interactivity!

I worked on a project like this using ggiraph and ggplot2 and shiny for BC Gov but it's not live yet (https://github.com/bcgov/protected-lands-and-waters-indicator/tree/steffi-indicator)

**Comment by psolymos** [comment]
@steffilazerte I checkedd off 2 items:

- Cell to plot should omit or identify surveyed blocks: the plotting function displays the title and prints out the observed count. I am getting an `subscript out of bounds` error in the app for this plot that I could not reproduce in the CLI-only.
- Table row names should be words (rather than N, A, D): here I used inds/km^2 (and not per 1000 km^2), digits were weird for such small densities.

I also fixed #8, univariate CART labels look good now.

Regarding the PI reporting I have several suggestions:

1. the Summary needs more width, move Options to the bottom to make room for the Summary
2. plots are all right, I suggest making a new tab for the interactive map+table exploration and leave the current plots as is
3. the info from `mc_get_pred(PI)` is what we want to present, especially `$data` and `$total` (maybe `$boot_full`), I imagine this to be saved at the end into a multi-sheet Excel file but I am waiting for additional feedback regarding the PI output subsetting (there is an `ss` argument for this) and this is relatively straightforward to add, I have snippets if you need it.

Please go ahead and mock up the ggiraph piece! Thanks.

**Comment by steffilazerte** [comment]
Hi Peter,

- I fixed the table formatting
- I fixed the cell reference problem (in total.R, it still referred to 'N', not the 'Total_Moose')
- I started a DT to ggiraph map. It works, if you select a a row in the Data table it highlights the cell on the map, but definitely still needs some finesse. What column represents the "error" they wanted to search by? I could add that to the tool tip. Right now you can also click on the map the change the selection. I think that's okay, but will have to make sure the DT updates accordingly. Also, should we omit some columns from the DT to make things clearer? 

It's not there yet, but I'm signing off for the weekend and wanted you to have the chance to see the mock up without having to wait until Monday (but don't work on the weekend on my account!). Happy weekend 😸

**Comment by psolymos** [comment]
Thanks @steffilazerte I will check. I can confirm that there will be no other modifications to the filtering options in this round. We might revisit that later. Enjoy the nice fall weather outside!

**Comment by psolymos** [comment]
@steffilazerte merging this PR so that I can more easily tweak some minor things on my end and I want to add the table download functionality.

Let's open a new PR for the PI exploration.

**Review by psolymos — APPROVED** [review]

**Pull request merged**
